// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: product/v1/product.proto

package productv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ProductService_GetProduct_FullMethodName     = "/product.v1.ProductService/GetProduct"
	ProductService_GetProductList_FullMethodName = "/product.v1.ProductService/GetProductList"
	ProductService_FillCart_FullMethodName       = "/product.v1.ProductService/FillCart"
)

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductServiceClient interface {
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
	GetProductList(ctx context.Context, in *GetProductListRequest, opts ...grpc.CallOption) (ProductService_GetProductListClient, error)
	FillCart(ctx context.Context, opts ...grpc.CallOption) (ProductService_FillCartClient, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductResponse)
	err := c.cc.Invoke(ctx, ProductService_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProductList(ctx context.Context, in *GetProductListRequest, opts ...grpc.CallOption) (ProductService_GetProductListClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProductService_ServiceDesc.Streams[0], ProductService_GetProductList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &productServiceGetProductListClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProductService_GetProductListClient interface {
	Recv() (*Product, error)
	grpc.ClientStream
}

type productServiceGetProductListClient struct {
	grpc.ClientStream
}

func (x *productServiceGetProductListClient) Recv() (*Product, error) {
	m := new(Product)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *productServiceClient) FillCart(ctx context.Context, opts ...grpc.CallOption) (ProductService_FillCartClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProductService_ServiceDesc.Streams[1], ProductService_FillCart_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &productServiceFillCartClient{ClientStream: stream}
	return x, nil
}

type ProductService_FillCartClient interface {
	Send(*Product) error
	CloseAndRecv() (*Cart, error)
	grpc.ClientStream
}

type productServiceFillCartClient struct {
	grpc.ClientStream
}

func (x *productServiceFillCartClient) Send(m *Product) error {
	return x.ClientStream.SendMsg(m)
}

func (x *productServiceFillCartClient) CloseAndRecv() (*Cart, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Cart)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProductServiceServer is the server API for ProductService service.
// All implementations must embed UnimplementedProductServiceServer
// for forward compatibility
type ProductServiceServer interface {
	GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error)
	GetProductList(*GetProductListRequest, ProductService_GetProductListServer) error
	FillCart(ProductService_FillCartServer) error
	mustEmbedUnimplementedProductServiceServer()
}

// UnimplementedProductServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (UnimplementedProductServiceServer) GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedProductServiceServer) GetProductList(*GetProductListRequest, ProductService_GetProductListServer) error {
	return status.Errorf(codes.Unimplemented, "method GetProductList not implemented")
}
func (UnimplementedProductServiceServer) FillCart(ProductService_FillCartServer) error {
	return status.Errorf(codes.Unimplemented, "method FillCart not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}

// UnsafeProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServiceServer will
// result in compilation errors.
type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProductList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetProductListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProductServiceServer).GetProductList(m, &productServiceGetProductListServer{ServerStream: stream})
}

type ProductService_GetProductListServer interface {
	Send(*Product) error
	grpc.ServerStream
}

type productServiceGetProductListServer struct {
	grpc.ServerStream
}

func (x *productServiceGetProductListServer) Send(m *Product) error {
	return x.ServerStream.SendMsg(m)
}

func _ProductService_FillCart_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProductServiceServer).FillCart(&productServiceFillCartServer{ServerStream: stream})
}

type ProductService_FillCartServer interface {
	SendAndClose(*Cart) error
	Recv() (*Product, error)
	grpc.ServerStream
}

type productServiceFillCartServer struct {
	grpc.ServerStream
}

func (x *productServiceFillCartServer) SendAndClose(m *Cart) error {
	return x.ServerStream.SendMsg(m)
}

func (x *productServiceFillCartServer) Recv() (*Product, error) {
	m := new(Product)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProductService_ServiceDesc is the grpc.ServiceDesc for ProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.v1.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProduct",
			Handler:    _ProductService_GetProduct_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetProductList",
			Handler:       _ProductService_GetProductList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FillCart",
			Handler:       _ProductService_FillCart_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "product/v1/product.proto",
}
